# Generated by Django 4.2.4 on 2023-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('car_cc', models.CharField(max_length=200)),
                ('car_transmission', models.CharField(max_length=200)),
                ('car_color', models.CharField(max_length=200)),
                ('car_hp', models.CharField(max_length=200)),
                ('car_torque', models.CharField(max_length=200)),
            ],
        ),
    ]
