# Generated by Django 4.2.4 on 2023-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_cc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_hp',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_torque',
            field=models.FloatField(max_length=200),
        ),
    ]
